# Generated by Django 5.0.6 on 2024-06-01 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("systems", "0002_hydroponicssystem_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pH_data",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The pH level of the nutrient solution,"
                        " should be between 0 and 14.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "water_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The water temperature in Celsius,"
                        " should be between 0°C and 45°C.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "TDS",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The Total Dissolved Solids (TDS) in ppm,"
                        " should be between 0 and 2000 ppm.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this measurement was taken.",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        help_text="The hydroponics system associated with this measurement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="systems.hydroponicssystem",
                    ),
                ),
            ],
        ),
    ]
